chore : 로그 추가!

diff --git a/.github/workflows/workflows.yml b/.github/workflows/workflows.yml
--- a/.github/workflows/workflows.yml
+++ b/.github/workflows/workflows.yml
@@ -20,10 +20,24 @@ jobs:
           distribution: 'temurin'
           java-version: '21'
 
-      - name: Replace variables in application.yml
+      - name: Check if application.yml exists
         run: |
-          sed -i "s|\${SECURITY_USER_NAME}|${{ secrets.SECURITY_USER_NAME }}|g" ./src/main/resources/application.yml
-          sed -i "s|\${SECURITY_USER_PASSWORD}|${{ secrets.SECURITY_USER_PASSWORD }}|g" ./src/main/resources/application.yml
+            if [ -f ./src/main/resources/application.yml ]; then
+            echo "application.yml found"
+            cat ./src/main/resources/application.yml
+            else
+            echo "application.yml not found"
+            exit 1
+            fi
+            
+            - name: Fix permissions
+              run: |
+                chmod 644 ./src/main/resources/application.yml
+            
+            - name: Replace variables in application.yml
+              run: |
+                sed -i.bak "s|\${SECURITY_USER_NAME}|\"${{ secrets.SECURITY_USER_NAME }}\"|g" ./src/main/resources/application.yml
+                sed -i.bak "s|\${SECURITY_USER_PASSWORD}|\"${{ secrets.SECURITY_USER_PASSWORD }}\"|g" ./src/main/resources/application.yml
 
       - name: Build with Maven
         run: |
